[programs.devnet]
epicsolanaproject = "Dwxm1jJxwEuTCmRSzu6ixDQTNcZSXmyWsKPMoARoPZVk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/darshan/.config/solana/id.json"

[scripts]
test = "node tests/epicsolanaproject.js"
