[programs.localnet]
epicsolanaproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/darshan/.config/solana/id.json"

[scripts]
test = "node tests/epicsolanaproject.js"
